# Generated by Django 3.2.5 on 2021-08-29 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_newsstory_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsstory',
            name='image_url',
            field=models.URLField(default='https://unsplash.com/photos/rOkhGPBdmpk'),
        ),
    ]
